
# About the project

*Write a short description about the course and add a link to your GitHub repository here. This is an R Markdown (.Rmd) file so you should use R Markdown syntax.*

```{r}
# This is a so-called "R chunk" where you can write R code.

date()

```
The text continues here.

- Some thoughts avout IODS course:
"Cool"

### Reflect on learning experiences

We use existing R code examples or existing work for R exercise, this is real-wold programming and much more effecient. When I used R sometimes the command doesn't work because I forgot to motify variable type, it's really helpful for me to get more familiar with variable types in R, through practicing I could understand the clear identification of them.

I really like the approach using **RMarkdown**, I used it to show my analysis scripts and results to my colleagues. Also from my preference, I like the way `rmd` files present, we can scroll the rmd file to check the results instead of open `Plots` windows, it's really useful if we want to see the different of commands.


**My GitHub repository:**
*<https://github.com/xindhuan/IODS-project>*
